/**
 * Maps the lucide icon *names* used in data (e.g. `Suggestion.icon`) to components.
 * An explicit map keeps the bundle small (no whole-library import); unknown names get a neutral glyph.
 */
import {
  Activity,
  AlarmClock,
  Bell,
  BookUser,
  Brain,
  Bug,
  Calendar,
  CalendarDays,
  ChefHat,
  ClipboardList,
  CloudSun,
  Code,
  Eraser,
  ExternalLink,
  FileSearch,
  FolderInput,
  FolderSync,
  GitBranch,
  Globe,
  Hammer,
  Keyboard,
  Languages,
  type LucideIcon,
  type LucideProps,
  Mail,
  Mic,
  Monitor,
  Repeat,
  Scale,
  ScanEye,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  SpellCheck,
  Sunrise,
  Timer,
  UserRound,
  Users,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  bell: Bell,
  'book-user': BookUser,
  brain: Brain,
  bug: Bug,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'chef-hat': ChefHat,
  'clipboard-list': ClipboardList,
  'cloud-sun': CloudSun,
  code: Code,
  eraser: Eraser,
  'external-link': ExternalLink,
  'file-search': FileSearch,
  'folder-input': FolderInput,
  'folder-sync': FolderSync,
  'git-branch': GitBranch,
  globe: Globe,
  hammer: Hammer,
  keyboard: Keyboard,
  languages: Languages,
  mail: Mail,
  mic: Mic,
  monitor: Monitor,
  repeat: Repeat,
  scale: Scale,
  'scan-eye': ScanEye,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  'spell-check': SpellCheck,
  sunrise: Sunrise,
  timer: Timer,
  'user-round': UserRound,
  users: Users,
};

/** The handoff's icon choice per suggestion id (falls back to the catalogue's `icon`). */
export const SUGGESTION_ICON: Record<string, string> = {
  briefing: 'sunrise',
  today: 'calendar',
  'meeting-prep': 'users',
  timer: 'timer',
  remind: 'bell',
  alarm: 'alarm-clock',
  'summarise-clip': 'clipboard-list',
  'translate-clip': 'languages',
  'fix-clip': 'spell-check',
  dictate: 'mic',
  'reply-mail': 'mail',
  screen: 'monitor',
  'explain-error': 'bug',
  'find-doc': 'file-search',
  'tidy-downloads': 'folder-input',
  research: 'globe',
  compare: 'scale',
  shopping: 'shopping-cart',
  weather: 'cloud-sun',
  recipe: 'chef-hat',
  build: 'code',
  status: 'activity',
  'open-result': 'external-link',
  codex: 'git-branch',
  teach: 'brain',
  'what-you-know': 'user-round',
  'go-local': 'shield-check',
  'forget-today': 'eraser',
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const C = ICONS[name] ?? Sparkles;
  return <C aria-hidden="true" {...props} />;
}
