// GENERATED by packages/mcp/scripts/gen-relay-catalog.mjs from @jarvis/core McpTools — do not edit.
// Regenerate with: pnpm --filter @jarvis/mcp gen:relay

export interface CatalogTool {
  name: string;
  title: string;
  description: string;
  inputSchema: { type: 'object'; [key: string]: unknown };
  annotations: {
    title: string;
    readOnlyHint: boolean;
    destructiveHint: boolean;
    idempotentHint: boolean;
    openWorldHint: boolean;
  };
}

export const TOOL_CATALOG: readonly CatalogTool[] = [
  {
    name: 'jarvis_speak',
    title: 'Speak out loud',
    description: "Say a short message out loud on the user's computer (≤ 300 characters).",
    inputSchema: {
      type: 'object',
      properties: {
        text: {
          type: 'string',
          minLength: 1,
          maxLength: 300,
        },
      },
      required: ['text'],
    },
    annotations: {
      title: 'Speak out loud',
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_ask_user',
    title: 'Ask the user out loud',
    description:
      'Ask the user a question out loud and wait for their spoken or clicked answer. Use when you are blocked and need a decision.',
    inputSchema: {
      type: 'object',
      properties: {
        question: {
          type: 'string',
          minLength: 1,
          maxLength: 300,
        },
        options: {
          maxItems: 4,
          type: 'array',
          items: {
            type: 'string',
            minLength: 1,
            maxLength: 60,
          },
        },
        timeoutSeconds: {
          default: 120,
          type: 'integer',
          minimum: 10,
          maximum: 600,
        },
      },
      required: ['question'],
    },
    annotations: {
      title: 'Ask the user out loud',
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_notify',
    title: 'Show a desktop notification',
    description: 'Show a desktop notification to the user (silent).',
    inputSchema: {
      type: 'object',
      properties: {
        title: {
          type: 'string',
          minLength: 1,
          maxLength: 80,
        },
        body: {
          default: '',
          type: 'string',
          maxLength: 300,
        },
      },
      required: ['title'],
    },
    annotations: {
      title: 'Show a desktop notification',
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_start_task',
    title: 'Start a background task',
    description:
      "Start a background task on the user's computer with Jarvis (Claude Code, Codex or the Home agent). Risky steps still require the user's approval on their screen.",
    inputSchema: {
      type: 'object',
      properties: {
        task: {
          type: 'string',
          minLength: 1,
          maxLength: 4000,
        },
        project: {
          type: 'string',
          maxLength: 80,
        },
        agent: {
          type: 'string',
          enum: ['claude', 'codex', 'home'],
        },
      },
      required: ['task'],
    },
    annotations: {
      title: 'Start a background task',
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_list_sessions',
    title: 'List Jarvis sessions',
    description: 'List Jarvis background sessions with their status and latest activity.',
    inputSchema: {
      type: 'object',
      properties: {},
    },
    annotations: {
      title: 'List Jarvis sessions',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_session_result',
    title: 'Get a session result',
    description: 'Get the final result text of a Jarvis session.',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          minLength: 1,
        },
      },
      required: ['id'],
    },
    annotations: {
      title: 'Get a session result',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_remember',
    title: 'Remember a fact',
    description: 'Save a durable preference or fact about the user in Jarvis memory.',
    inputSchema: {
      type: 'object',
      properties: {
        text: {
          type: 'string',
          minLength: 1,
          maxLength: 300,
        },
      },
      required: ['text'],
    },
    annotations: {
      title: 'Remember a fact',
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  {
    name: 'jarvis_recall',
    title: 'Recall remembered facts',
    description: 'List what Jarvis remembers about the user (preferences and facts).',
    inputSchema: {
      type: 'object',
      properties: {},
    },
    annotations: {
      title: 'Recall remembered facts',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
];
